### ISSUE TITLE
when running is finished fragment_running should send the information

### ISSUE THREAD

**Issue by Kchanghun** [Kchanghun/UU#30]
fragment_running sends bunch of data to MainActivity every single time when running is finished.
But for recognizing where to put data ( was that for crew Fittest? or personal Fittest?),
fragment_running should send one more data like
           int who;
if who means crew, then who = 0
else if who means personal, then who = 1

**Comment by Kchanghun** [comment]
For now I just make MainActivity put every data to personal Fittest

**Comment by qkralsrl1029** [comment]
I wonder if I got your question correctly, there are some data that works  interactive. 
For example, total running distance is saved at not only local storage, also firebase server. 
So It is difficult to classify data by its uses.
Just use as whatever you want!

**Comment by Kchanghun** [comment]
fuck, I fixed
